services:
  mysql:
    image: mysql:8
    platform: linux/arm64
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: python:3.9  # ここを python:3.9 にすればPythonになる
    platform: linux/arm64
    container_name: app
    restart: always
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    platform: linux/arm64
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin:latest
    platform: linux/arm64
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
